// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for First Row documents
 */
interface FirstRowDocumentData {
  /**
   * Heading field in *First Row*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Sub Heading field in *First Row*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row.sub_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Data field in *First Row*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row.data
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  data: prismic.DateField;
}

/**
 * First Row document from Prismic
 *
 * - **API ID**: `first_row`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FirstRowDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FirstRowDocumentData>,
    "first_row",
    Lang
  >;

/**
 * Content for First Row Slice documents
 */
interface FirstRowSliceDocumentData {
  /**
   * Heading field in *First Row Slice*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_slice.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Sub Heading field in *First Row Slice*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_slice.sub_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;
}

/**
 * First Row Slice document from Prismic
 *
 * - **API ID**: `first_row_slice`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FirstRowSliceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FirstRowSliceDocumentData>,
    "first_row_slice",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | ThirdRowSlice
  | FirstRowSlicedSlice
  | SecondRowSliceSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for SecondRowSlice documents
 */
interface SecondrowsliceDocumentData {
  /**
   * Heading field in *SecondRowSlice*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secondrowslice.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Sub Heading field in *SecondRowSlice*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secondrowslice.sub_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;
}

/**
 * SecondRowSlice document from Prismic
 *
 * - **API ID**: `secondrowslice`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SecondrowsliceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SecondrowsliceDocumentData>,
    "secondrowslice",
    Lang
  >;

/**
 * Content for ThirdRowSlice documents
 */
interface ThirdrowsliceDocumentData {
  /**
   * Heading field in *ThirdRowSlice*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: thirdrowslice.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Second Heading field in *ThirdRowSlice*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: thirdrowslice.second_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_heading: prismic.KeyTextField;
}

/**
 * ThirdRowSlice document from Prismic
 *
 * - **API ID**: `thirdrowslice`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ThirdrowsliceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ThirdrowsliceDocumentData>,
    "thirdrowslice",
    Lang
  >;

export type AllDocumentTypes =
  | FirstRowDocument
  | FirstRowSliceDocument
  | HomepageDocument
  | SecondrowsliceDocument
  | ThirdrowsliceDocument;

/**
 * Primary content in *FirstRowSliced → Default → Primary*
 */
export interface FirstRowSlicedSliceDefaultPrimary {
  /**
   * Heading field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Second Heading field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.second_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_heading: prismic.RichTextField;

  /**
   * Option One field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.option_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  option_one: prismic.RichTextField;

  /**
   * Option Two field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.option_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  option_two: prismic.RichTextField;

  /**
   * Option Three field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.option_three
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  option_three: prismic.RichTextField;

  /**
   * Option Four field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.option_four
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  option_four: prismic.RichTextField;

  /**
   * Option Five field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.option_five
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  option_five: prismic.RichTextField;

  /**
   * Option Six field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.option_six
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  option_six: prismic.RichTextField;

  /**
   * Second Box Heading field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.second_box_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_box_heading: prismic.TitleField;

  /**
   * Second Box Sub Heading field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.second_box_sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_box_sub_heading: prismic.RichTextField;

  /**
   * Validation field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.validation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  validation: prismic.RichTextField;

  /**
   * Not Validation field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.not_validation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  not_validation: prismic.RichTextField;

  /**
   * Date field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.date
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  date: prismic.RichTextField;

  /**
   * Number Zero field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.number_zero
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  number_zero: prismic.RichTextField;

  /**
   * Number Four field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.number_four
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  number_four: prismic.RichTextField;

  /**
   * Slice field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.slice
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  slice: prismic.ContentRelationshipField<"first_row_slice">;

  /**
   * Done field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.done
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  done: prismic.RichTextField;

  /**
   * Warning field in *FirstRowSliced → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_row_sliced.default.primary.warning
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  warning: prismic.RichTextField;
}

/**
 * Default variation for FirstRowSliced Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FirstRowSlicedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FirstRowSlicedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FirstRowSliced*
 */
type FirstRowSlicedSliceVariation = FirstRowSlicedSliceDefault;

/**
 * FirstRowSliced Shared Slice
 *
 * - **API ID**: `first_row_sliced`
 * - **Description**: FirstRowSliced
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FirstRowSlicedSlice = prismic.SharedSlice<
  "first_row_sliced",
  FirstRowSlicedSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Sub Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.TitleField;

  /**
   * Top Para field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.top_para
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_para: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *SecondRowSlice → Default → Primary*
 */
export interface SecondRowSliceSliceDefaultPrimary {
  /**
   * Heading field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Sub Heading field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Without Green field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.without_green
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  without_green: prismic.RichTextField;

  /**
   * With Green field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.with_green
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  with_green: prismic.RichTextField;

  /**
   * Graph Height field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.graph_height
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  graph_height: prismic.RichTextField;

  /**
   * Graph Second Height field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.graph_second_height
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  graph_second_height: prismic.RichTextField;

  /**
   * Graph Third Height field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.graph_third_height
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  graph_third_height: prismic.RichTextField;

  /**
   * SecondSlice field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.secondslice
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondslice: prismic.ContentRelationshipField<"secondrowslice">;

  /**
   * Second Heading field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.second_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_heading: prismic.TitleField;

  /**
   * Second Sub Heading field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.second_sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_sub_heading: prismic.RichTextField;

  /**
   * ThirdHeading field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.thirdheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  thirdheading: prismic.TitleField;

  /**
   * Third Sub Heading field in *SecondRowSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_row_slice.default.primary.third_sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  third_sub_heading: prismic.RichTextField;
}

/**
 * Default variation for SecondRowSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondRowSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecondRowSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecondRowSlice*
 */
type SecondRowSliceSliceVariation = SecondRowSliceSliceDefault;

/**
 * SecondRowSlice Shared Slice
 *
 * - **API ID**: `second_row_slice`
 * - **Description**: SecondRowSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondRowSliceSlice = prismic.SharedSlice<
  "second_row_slice",
  SecondRowSliceSliceVariation
>;

/**
 * Primary content in *ThirdRow → Default → Primary*
 */
export interface ThirdRowSliceDefaultPrimary {
  /**
   * Heading field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Second Heading field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.second_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_heading: prismic.RichTextField;

  /**
   * First Logo field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.first_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  first_logo: prismic.ImageField<never>;

  /**
   * label field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  label: prismic.ContentRelationshipField;

  /**
   * Second Logo field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.second_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  second_logo: prismic.ImageField<never>;

  /**
   * Third Logo field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.third_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  third_logo: prismic.ImageField<never>;

  /**
   * Fourth field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.fourth
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fourth: prismic.ImageField<never>;

  /**
   * Fifth Logo field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.fifth_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fifth_logo: prismic.ImageField<never>;

  /**
   * Sixth Logo field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.sixth_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  sixth_logo: prismic.ImageField<never>;

  /**
   * Seven Logo field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.seven_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  seven_logo: prismic.ImageField<never>;

  /**
   * Eight Logo field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.eight_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  eight_logo: prismic.ImageField<never>;

  /**
   * Second Box Heading field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.second_box_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_box_heading: prismic.TitleField;

  /**
   * ParagraphDiscription field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.paragraphdiscription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraphdiscription: prismic.RichTextField;

  /**
   * Box Image field in *ThirdRow → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: third_row.default.primary.box_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  box_image: prismic.ImageField<never>;
}

/**
 * Default variation for ThirdRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThirdRowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ThirdRowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ThirdRow*
 */
type ThirdRowSliceVariation = ThirdRowSliceDefault;

/**
 * ThirdRow Shared Slice
 *
 * - **API ID**: `third_row`
 * - **Description**: ThirdRow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThirdRowSlice = prismic.SharedSlice<
  "third_row",
  ThirdRowSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FirstRowDocument,
      FirstRowDocumentData,
      FirstRowSliceDocument,
      FirstRowSliceDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SecondrowsliceDocument,
      SecondrowsliceDocumentData,
      ThirdrowsliceDocument,
      ThirdrowsliceDocumentData,
      AllDocumentTypes,
      FirstRowSlicedSlice,
      FirstRowSlicedSliceDefaultPrimary,
      FirstRowSlicedSliceVariation,
      FirstRowSlicedSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      SecondRowSliceSlice,
      SecondRowSliceSliceDefaultPrimary,
      SecondRowSliceSliceVariation,
      SecondRowSliceSliceDefault,
      ThirdRowSlice,
      ThirdRowSliceDefaultPrimary,
      ThirdRowSliceVariation,
      ThirdRowSliceDefault,
    };
  }
}
