// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  first_row_sliced: dynamic(() => import("./FirstRowSliced")),
  hero: dynamic(() => import("./Hero")),
  second_row_slice: dynamic(() => import("./SecondRowSlice")),
  third_row: dynamic(() => import("./ThirdRow")),
};
